name: ci-cd-MaxMur-Site

on:
  push:
    branches: [ main ]

jobs:
  CI:
    runs-on: ubuntu-latest
    container:
            image: ubuntu:20.04

    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Run nginx server
        run: |
                apt update && apt install nginx wget -y 
                cp -r my_site/maxmur /var/www/html
                service nginx start 
                wget localhost
  CD:
    runs-on: ubuntu-latest
    
    needs: [CI]
    
    steps:
    - name: Deploy GitBook in server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: cd /home/maxmur/my_site/; git pull; cd /home/maxmur/my_site/docker/; docker-compose up -d --force-recreate
